version: '3.8'

services:
  mongodb:
    container_name: dino-mongodb
    image: mongo
    restart: always
    volumes:
      - ./local-storage/mongodb:/data/db
    ports:
      - 27017:27017

  localstack:
    container_name: dino-localstack
    image: localstack/localstack
    ports:
      - 4510-4559:4510-4559
      - 4566:4566
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./local-storage/localstack:/tmp/localstack
